#!/bin/bash
BOOST_HOME="$MEMSURFER_INSTALL/NCI-DOE-Collab-Pilot2-MemSurfer/external"
BOOSTLIB="$BOOST_HOME/lib"
BOOSTINC="$BOOST_HOME/include"
export BOOSTLIB=$BOOSTLIB
export LIBRARY_PATH="$BOOSTLIB:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$BOOSTLIB:$LD_LIBRARY_PATH"
export LD_RUN_PATH="$BOOSTLIB:$LD_RUN_PATH"
export CMAKE_LIBRARY_PATH="$BOOSTLIB:$CMAKE_LIBRARY_PATH"
export CMAKE_INCLUDE_PATH="$BOOSTINC:$CMAKE_INCLUDE_PATH"
export CPATH="$BOOSTINC:$CPATH"
